Feature/add readme
nocsland/urfu_mlops pull request #18
Opened 2024-05-13 19:48 UTC by 01Evgeniy

Добавил описание README.md

2024-05-13 20:30 UTC, nocsland commented on translator/README.md
> +12. Автоматизация с GitHub Actions: Мы интегрировали наш Jenkins Pipeline с GitHub Actions, чтобы автоматизировать процесс сборки и тестирования. Это обеспечивает непрерывную
Причем тут GitHub Actions? Автоматическая сборка происходит на основании вебхуков которые нам действительно присылает github, но не GitHub Actions.

2024-05-13 20:36 UTC, nocsland commented on translator/README.md
> +4. Манипуляции с датасетом: Применяя различные техники версионирования, мы демонстрируем, как можно эффективно управлять и обновлять датасеты в процессе разработки.
С датасетом, в данном случае, у нас одна операция, мы его скачиваем, хотя предварительно мы действительно провели некоторые операции с ним.

2024-05-13 20:42 UTC, nocsland requested changes

2024-05-13 20:42 UTC, nocsland commented on translator/README.md
Где хотя бы пару слов о том как запустить сборку вручную? Где условия в каком случае сборка собирается автоматически?

2024-05-14 19:08 UTC, nocsland commented on translator/README.md
> +
Добавь пункт из предыдущей версии readme мне кажется он необходим

## Использование API

После запуска приложения вы можете использовать следующие эндпоинты для перевода текста:

- **POST /translate/ru-to-en/**: Перевод текста с русского на английский.
- **POST /translate/en-to-ru/**: Перевод текста с английского на русский.

Пример запроса:
```
json { "text": "Привет, мир!" }
```

Ответ:
```
json { "translated_text": "Hello, world!" }
```

2024-05-14 19:27 UTC, ardubovik commented on translator/README.md
> +
Может зависимости добавить ?:

fastapi
uvicorn
pydantic
requests
sacremoses
dvc
dvc-gdrive
sentencepiece
transformers[torch]
httpx
pytest
pandas
allure-pytest

2024-05-14 19:31 UTC, nocsland approved these changes
Все хорошо.

2024-05-14 20:00 UTC, nocsland commented on translator/README.md
> +
Нет зависимости тут не нужны они автоматом подтянутся из файла при запуске пайплайна, здесь перечислены приложения которые необходимо установить на сервер для корректной работы нашего пайплайна и приложения

2024-05-14 20:11 UTC, ardubovik commented on translator/README.md
> +
Тогда может убрать из списка dvc? эта либа же при установке из requirements ставится pip-ом

2024-05-14 20:24 UTC, merged